apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: fenceagentsremediationtemplates.fence-agents.medik8s.io
spec:
  group: fence-agents.medik8s.io
  names:
    kind: FenceAgentsRemediationTemplate
    listKind: FenceAgentsRemediationTemplateList
    plural: fenceagentsremediationtemplates
    singular: fenceagentsremediationtemplate
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: FenceAgentsRemediationTemplate is the Schema for the fenceagentsremediationtemplates
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: FenceAgentsRemediationTemplateSpec defines the desired state
              of FenceAgentsRemediationTemplate
            properties:
              agent:
                description: Agent is the type of fence agent that will be used
                type: string
              nodeparameters:
                additionalProperties:
                  properties:
                    nodenamevaluemapping:
                      additionalProperties:
                        type: string
                      type: object
                  required:
                  - nodenamevaluemapping
                  type: object
                description: NodeParameters are node specific they are passed to the
                  fencing agent according to the node that is fenced
                type: object
              sharedparameters:
                additionalProperties:
                  type: string
                description: SharedParameters are passed to the fencing agent no matter
                  which node is fenced (i.e they are common for all the nodes)
                type: object
            required:
            - agent
            type: object
          status:
            description: FenceAgentsRemediationTemplateStatus defines the observed
              state of FenceAgentsRemediationTemplate
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
